version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip3 install -r requirements-dev.txt

  build:
    commands:
      - pylint --load-plugins pylint_django --django-settings-module=hairdresser_django.settings --ignore=migrations appointments/
      - coverage run --source='.' manage.py test appointments
      - coverage xml

reports:
  UnitTests:
    files:
      - 'unittests.xml'
  NewCoverage:
    files:
      - 'coverage.xml'
    file-format: COBERTURAXML